# Importing numpy library

In [1]:
import numpy as np

# Creating numpy arrays

# One dimensional arrays

In [2]:
L=[23,33,35,56,67,78]
arr=np.array(L)
print(arr)

[23 33 35 56 67 78]


In [3]:
arr

array([23, 33, 35, 56, 67, 78])

In [4]:
arr*2

array([ 46,  66,  70, 112, 134, 156])

In [5]:
L*2


[23, 33, 35, 56, 67, 78, 23, 33, 35, 56, 67, 78]

In [6]:
L1=[5,6,7]
L2=[2,6,1]
arr1=np.array(L1)
arr2=np.array(L2)

In [7]:
arr1+arr2

array([ 7, 12,  8])

# Two dimensional arrays

In [8]:
L=[[12,22,23],[56,54,77]]
arr=np.array(L)
print(arr)

[[12 22 23]
 [56 54 77]]


In [9]:
arr

array([[12, 22, 23],
       [56, 54, 77]])

In [11]:
L=[[2,3,4],[5,6,7],[8,7,9]]  
arr1=np.array(L)
arr1

array([[2, 3, 4],
       [5, 6, 7],
       [8, 7, 9]])

# Array properties

In [12]:
arr1=np.array([23,33,35,56,67,78])
arr2=np.array([[12,22,23],[56,54,77]])

In [13]:
arr1[1]

33

In [15]:
arr2[0,2]

23

In [16]:
arr2[1:,1:]

array([[54, 77]])

In [18]:
arr2[0,0]= 30
arr2

array([[30, 22, 23],
       [56, 54, 77]])

# Shape of the array

In [19]:
print(arr1.shape)
print(arr2.shape)

(6,)
(2, 3)


# Dimensions of the array

In [20]:
print(arr1.ndim)
print(arr2.ndim)

1
2


# Data type inside arrays

In [21]:
print(arr1.dtype)
print(arr2.dtype)

int32
int32


# Size of arrays

In [22]:
print(arr1.size)
print(arr2.size)

6
6


# Special arrays

# Null array

In [23]:
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [24]:
b=np.zeros((3,3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Ones array

In [25]:
a=np.ones(20)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [26]:
b=np.ones((5,5))
print(b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# Identity matrix

In [27]:
I3=np.eye(3)
print(I3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Simulating random integers

In [34]:
r=np.random.randint(2,8) #One random integer from 2 to 8

In [35]:
r


7

In [36]:
r=np.random.randint(2,8,10) #10 random integers from 2 to 8

In [37]:
r

array([6, 3, 2, 5, 2, 7, 6, 3, 5, 3])

# Simulating random floats from 0 to 1

In [38]:
r=np.random.random(5)

In [39]:
r

array([0.02375233, 0.54751191, 0.14535693, 0.83901485, 0.2877088 ])

In [40]:
r=np.random.random((5,5))

In [41]:
r

array([[0.86942451, 0.39131455, 0.46980176, 0.49978204, 0.41613836],
       [0.6107823 , 0.90686968, 0.54611678, 0.43423931, 0.08543465],
       [0.09154386, 0.2493652 , 0.61812251, 0.88035913, 0.17534084],
       [0.3002548 , 0.22099922, 0.9057895 , 0.97260481, 0.3164731 ],
       [0.17749417, 0.85469981, 0.54316347, 0.83684815, 0.79171706]])

# Simulating random floats from standard normal distribution

In [42]:
r=np.random.randn(10)

In [43]:
r

array([ 0.59325473, -0.7388824 ,  0.77541747, -1.55852264, -0.6444268 ,
        0.21513914,  0.90366228,  0.14826914,  0.4125913 ,  0.19698791])

In [44]:
r=np.random.randn(3,3)

In [45]:
r

array([[-1.41670213, -1.40920742, -1.06306048],
       [ 1.87844393, -1.43854282,  0.21136513],
       [-0.53898778,  0.59689472, -0.62743785]])

# Simulating data from probability distributions

# Normal distribution

In [46]:
r=np.random.normal(50,5,4) #4 random values from a normal distribution with mean 50 and standard deviation 5

In [47]:
r

array([44.34155107, 45.94788215, 46.18082543, 49.29415294])

In [48]:
r=np.random.normal(50,5,(4,4))

In [49]:
r

array([[50.82851059, 51.46419171, 56.0640789 , 44.09075684],
       [54.01917705, 48.63748968, 53.60356178, 43.73445655],
       [51.55008945, 46.75713207, 45.98314399, 39.16900453],
       [42.72395541, 53.85921584, 44.69710133, 50.30915183]])

# Uniform distribution

In [50]:
r=np.random.uniform(10,20,5)

In [51]:
r

array([18.08244626, 13.87190168, 19.6679162 , 15.35736885, 10.81487986])

In [52]:
r=np.random.uniform(10,20,(5,5))

In [53]:
r

array([[13.98828595, 17.71714384, 10.69649332, 15.64016379, 10.61603044],
       [15.35675859, 17.43704645, 18.56845338, 19.80994744, 12.64352704],
       [12.96954464, 11.88399469, 17.25404599, 19.83040531, 17.6055148 ],
       [15.95246369, 12.07495677, 10.86445414, 19.93245295, 13.28854076],
       [14.11886832, 13.3419361 , 18.68441204, 16.80891087, 12.76298092]])

# Generating sequence

# arange function with single dimension

In [54]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
arr=np.arange(3,10)

In [56]:
arr

array([3, 4, 5, 6, 7, 8, 9])

# Changing the shape of the sequence array

In [57]:
arr=np.arange(20)
arr.shape=(4,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [58]:
arr=np.arange(20).reshape(4,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

# Creating Vectors

In [59]:
arr=np.array([12,23,34,43,44,45,56,32,33,56])
arr.shape=(10,1)
arr

array([[12],
       [23],
       [34],
       [43],
       [44],
       [45],
       [56],
       [32],
       [33],
       [56]])

In [60]:
arr=np.array([12,23,34,43,44,45,56,32,33,56]).reshape(10,1)
arr

array([[12],
       [23],
       [34],
       [43],
       [44],
       [45],
       [56],
       [32],
       [33],
       [56]])

# Indexing & slicing one dimensional numpy arrays

In [61]:
a=np.array([12,22,34,56,54,56])

In [62]:
a[0]

12

In [63]:
a[2]

34

In [64]:
a[-1]

56

In [65]:
a[2:5]

array([34, 56, 54])

In [66]:
a[3:]

array([56, 54, 56])

In [67]:
a[:3]

array([12, 22, 34])

In [68]:
a[::2]

array([12, 34, 54])

In [69]:
a[::-1]

array([56, 54, 56, 34, 22, 12])

# Indexing & slicing multi dimensional numpy arrays

In [70]:
b=np.array([[23,33,34,45,56],[23,33,34,56,54],[78,65,67,64,78]])
b

array([[23, 33, 34, 45, 56],
       [23, 33, 34, 56, 54],
       [78, 65, 67, 64, 78]])

In [71]:
b[0,3]

45

In [72]:
b[:2,1:4]

array([[33, 34, 45],
       [33, 34, 56]])

In [73]:
b[1,[2,4]]

array([34, 54])

# Numpy arrays are mutable

In [74]:
a=np.array([23,33,45,56,54])

In [75]:
a[0]=100

In [76]:
a

array([100,  33,  45,  56,  54])

# Array masking

In [77]:
a=np.array([34,45,33,23,45,67,65,78,21])

In [78]:
a>50

array([False, False, False, False, False,  True,  True,  True, False])

In [79]:
a[a>50]

array([67, 65, 78])

# Basic numpy functions

# numpy functions with scaler values

In [80]:
np.sin(12) #Trigonometry

-0.5365729180004349

In [81]:
np.log(10) #Log

2.302585092994046

In [82]:
np.power(4,2) #Power

16

In [83]:
np.exp(2) #Exponential values

7.38905609893065

In [84]:
np.round(34.567) #Rounding

35.0

# numpy functions with arrays

In [85]:
arr=np.array([34,33,21,25,56,32,44,78,12])

In [86]:
arr.min()

12

In [87]:
arr.max()

78

In [88]:
arr.mean()

37.22222222222222

In [89]:
arr.sort()
arr

array([12, 21, 25, 32, 33, 34, 44, 56, 78])

In [90]:
np.median(arr)

33.0

# Special numpy values

In [91]:
np.pi

3.141592653589793

In [92]:
np.e

2.718281828459045

In [93]:
np.inf

inf

In [94]:
np.NINF

-inf

In [95]:
np.nan

nan

# Stacking numpy arrays

# Vertical stacking & horizontal stacking

In [96]:
a=np.array([[3,4,5],[6,3,5]])
b=np.array([[2,3,7],[8,2,6]])

In [97]:
c=np.vstack((a,b))
print(c)

[[3 4 5]
 [6 3 5]
 [2 3 7]
 [8 2 6]]


In [98]:
d=np.hstack((a,b))
print(d)

[[3 4 5 2 3 7]
 [6 3 5 8 2 6]]


# Appending

In [ ]:
a=np.array([[3,4,5],[6,3,5]])
b=np.array([[2,3,7],[8,2,6]])

In [99]:
c=np.append(a,b,axis=0)
print(c)

[[3 4 5]
 [6 3 5]
 [2 3 7]
 [8 2 6]]


In [100]:
d=np.append(a,b,axis=1)
print(d)

[[3 4 5 2 3 7]
 [6 3 5 8 2 6]]


# Concatenation

In [101]:
a=np.array([[3,4,5],[6,3,5]])
b=np.array([[2,3,7],[8,2,6]])

In [102]:
c=np.concatenate((a,b),axis=0)
print(c)

[[3 4 5]
 [6 3 5]
 [2 3 7]
 [8 2 6]]


In [103]:
d=np.concatenate((a,b),axis=0)
print(d)

[[3 4 5]
 [6 3 5]
 [2 3 7]
 [8 2 6]]


# Tiling

In [104]:
a=np.array([23,34])
b=np.tile(a,(1,2))
print(b)

[[23 34 23 34]]


In [105]:
a=np.array([23,34])
b=np.tile(a,(2,2))
print(b)

[[23 34 23 34]
 [23 34 23 34]]


In [106]:
a=np.array([[23,34],[56,54]])
b=np.tile(a,(1,2))
print(b)

[[23 34 23 34]
 [56 54 56 54]]


# Splitting arrays

# Horizontal splitting

In [107]:
a=np.random.random((4,4))
a

array([[0.79774542, 0.58574873, 0.57894279, 0.61385914],
       [0.58690019, 0.20975613, 0.31054843, 0.67280003],
       [0.07877163, 0.87684597, 0.65832847, 0.32169352],
       [0.79736256, 0.62526359, 0.32378395, 0.05012001]])

In [108]:
b=np.hsplit(a,2)
b

[array([[0.79774542, 0.58574873],
        [0.58690019, 0.20975613],
        [0.07877163, 0.87684597],
        [0.79736256, 0.62526359]]),
 array([[0.57894279, 0.61385914],
        [0.31054843, 0.67280003],
        [0.65832847, 0.32169352],
        [0.32378395, 0.05012001]])]

# Vertical spliiting

In [109]:
a=np.random.random((4,4))
a

array([[0.71016813, 0.03826036, 0.37032038, 0.59078765],
       [0.2854126 , 0.99173933, 0.20492161, 0.28260788],
       [0.7684287 , 0.49132791, 0.33663752, 0.47125063],
       [0.84728682, 0.48042898, 0.60972496, 0.95719115]])

In [110]:
b=np.vsplit(a,2)
b

[array([[0.71016813, 0.03826036, 0.37032038, 0.59078765],
        [0.2854126 , 0.99173933, 0.20492161, 0.28260788]]),
 array([[0.7684287 , 0.49132791, 0.33663752, 0.47125063],
        [0.84728682, 0.48042898, 0.60972496, 0.95719115]])]

# Rolling array elements

In [111]:
arr=np.array([1,2,3,4])
np.roll(arr,1)

array([4, 1, 2, 3])

In [112]:
arr=np.array([1,2,3,4])
np.roll(arr,2)

array([3, 4, 1, 2])

# Changing the data type

In [113]:
a=np.array([12.34,23.46,32.56])
b=a.astype(int)
b

array([12, 23, 32])

In [114]:
a=np.array(["12.34","23.46","32.56"])
b=a.astype(float)
b

array([12.34, 23.46, 32.56])

# Matrix operations

# Scaler multiplication

In [115]:
m1=np.array([[12,22,23],[45,43,33]])
3*m1

array([[ 36,  66,  69],
       [135, 129,  99]])

# Matrix addition & substraction

In [116]:
m1=np.array([10,20,30,40])
m2=np.array([30,40,50,60])

In [117]:
m1+m2

array([ 40,  60,  80, 100])

In [118]:
m1-m2

array([-20, -20, -20, -20])

In [119]:
m1=np.array([[12,22,23],[45,43,33]])
m2=np.array([[22,21,43],[46,23,13]])

In [120]:
m1+m2

array([[34, 43, 66],
       [91, 66, 46]])

In [121]:
m1-m2

array([[-10,   1, -20],
       [ -1,  20,  20]])

# Broadcasting

In [122]:
m1=np.array([10,20,30,40])

In [123]:
m1=m1+100
m1

array([110, 120, 130, 140])

# Matrix multiplication

In [124]:
m1=np.array([[12,23],[10,25]])
m2=np.array([[10,15],[5,15]])

In [125]:
m1*m2 #Hadamard product

array([[120, 345],
       [ 50, 375]])

In [126]:
np.dot(m1,m2)

array([[235, 525],
       [225, 525]])

In [127]:
m1.dot(m2)

array([[235, 525],
       [225, 525]])

In [128]:
np.dot(m2,m1)

array([[270, 605],
       [210, 490]])

In [129]:
m2.dot(m1)

array([[270, 605],
       [210, 490]])

# Trace of a matrix

In [130]:
m1=np.array([[12,23],[10,25]])

In [131]:
np.trace(m1)

37

# Diagonal elements of a square matrix

In [132]:
m1=np.array([[12,23],[10,25]])

In [133]:
np.diag(m1)

array([12, 25])

# Matrix transpose

In [134]:
m1=np.array([[12,23],[10,25]])
np.transpose(m1)

array([[12, 10],
       [23, 25]])

# Determinant of a matrix

In [135]:
m1=np.array([[12,23],[10,25]])
np.linalg.det(m1)

69.99999999999996

In [136]:
m2=np.array([[12,23,45],[10,25,15],[10,20,30]])
np.linalg.det(m2)

-299.99999999999943

# Inverse of a matrix

In [137]:
m1=np.array([[12,23],[10,25]])
np.linalg.inv(m1)

array([[ 0.35714286, -0.32857143],
       [-0.14285714,  0.17142857]])

In [138]:
m2=np.array([[12,23,45],[10,25,15],[10,20,30]])
np.linalg.inv(m2)

array([[-1.5       , -0.7       ,  2.6       ],
       [ 0.5       ,  0.3       , -0.9       ],
       [ 0.16666667,  0.03333333, -0.23333333]])